=== vchicor0d/vchicor0d.github.io/cv/cv_data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="cv"> <!-- Siempre que definamos un elemento, le tenemos que dar un nombre con el atributo name -->
    <xs:complexType mixed="true"> <!-- Si un elemento tiene atributos, otros elementos y/o texto combinados, es complexType y mixed="true" -->
      <xs:sequence> <!-- Con sequence los elementos que vengan tienen que existir en el orden en el que son definidos -->
	<xs:element name="photo" type="xs:string"/> <!-- Un elemento de un tipo base incluye el atributo type -->
	<xs:element name="name" type="xs:string"/>
	<xs:element name="address" type="xs:string"/>
	<xs:element name="email" type="xs:string"/>
	<xs:element name="tlf" type="xs:string"/>
	<xs:element name="summary" type="xs:string" minOccurs="0"/> <!-- Si un elemento es opcional, se le da un valor de minOccurs="0", por defecto es 1, es decir, como mínimo tiene que aparecer 1 vez -->
	<xs:element name="educations" minOccurs="0" maxOccurs="3"> <!-- Si un elemento puede ocurrir mas de una vez, se le da un valor de maxOccurs, en este caso 3 porque puede aparecer un máximo de 3 veces, el valor por defecto es 1, es decir, sólo puede aparecer una vez -->
	  <xs:complexType mixed="true">
	    <xs:sequence>
	      <xs:element name="education" maxOccurs="unbounded"> <!-- Si un elemento puede ocurrir un número indeterminado de veces, se le da un valor de maxOccurs="unbounded" -->
		<xs:complexType mixed="true">
		  <xs:all> <!-- Con all los elementos que vengan tienen que existir, pero pueden estar en cualquier orden -->
		    <xs:element name="course" type="xs:string"/>
		    <xs:element name="institution" type="xs:string"/>
		  </xs:all>
		  <xs:attribute name="start" type="xs:string" use="required"/> <!-- Para definir un atributo de una etiqueta se hace con attribute, se le da un nombre y un tipo y si queremos que sea obligatorio le damos use="required", por defecto no lo es -->
		  <xs:attribute name="end" type="xs:string" use="required"/>
		</xs:complexType>
	      </xs:element>
	    </xs:sequence>
	    <xs:attribute name="type" use="required"> <!-- Un atributo también puede ser de un tipo que no sea basico -->
	      <xs:simpleType> <!-- Con simpleType podemos añadir restricciones a los valores de un elemento (o atributo, en este caso) -->
		<xs:restriction base="xs:string"> <!-- Con restriction decimos que vamos a crear una restricción, el atributo base="xs:string" nos indica que los valores que tomará el elemento serán de este tipo -->
		  <xs:enumeration value="academic"/> <!-- Con enumeration enumeramos los posibles valores que podrá tomar el elemento con el atributo value -->
		  <xs:enumeration value="complementary"/>
		  <xs:enumeration value="other"/>
		</xs:restriction>
	      </xs:simpleType>
	    </xs:attribute>
	  </xs:complexType>
	</xs:element>
	<xs:element name="experiences" minOccurs="0">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="experience" maxOccurs="unbounded">
		<xs:complexType>
		  <xs:all>
		    <xs:element name="company" type="xs:string"/>
		    <xs:element name="projects">
		      <xs:complexType>
			<xs:sequence>
			  <xs:element name="project" maxOccurs="unbounded">
			    <xs:complexType mixed="true">
      			      <xs:sequence>
				<xs:element name="description" type="xs:string"/>
			      </xs:sequence>
			      <xs:attribute name="title" type="xs:string" use="required"/>
			      <xs:attribute name="workplace" type="xs:string" use="required"/>
			      <xs:attribute name="start" type="xs:string" use="required"/>
			      <xs:attribute name="end" type="xs:string" use="required"/>
			    </xs:complexType>
			  </xs:element>
			</xs:sequence>
		      </xs:complexType>
		    </xs:element>
		  </xs:all>
		</xs:complexType>
	      </xs:element>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
	<xs:element name="languages" minOccurs="0">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="language" maxOccurs="unbounded">
		<xs:complexType mixed="true">
		  <xs:attribute name="level" use="required"/>
		</xs:complexType>
	      </xs:element>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
	<xs:element name="skills" minOccurs="0">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
      </xs:sequence>
      <xs:attribute name="lang" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vchicor0d/vchicor0d.github.io/cv/cv_data_es.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cv_en.xsl"?>
<cv lang="es" color="teal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="cv_data.xsd">
  <photo>photo.jpg</photo>
  <name>Víctor Chico Rodríguez</name>
  <address>Calle Francisco Salzillo 7, 28850 Torrejón de Ardoz (Madrid)</address>
  <email>vchicorod@gmail.com</email>
  <tlf>610664565</tlf>
  <summary>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a faucibus est. Suspendisse pulvinar erat id orci viverra, id ullamcorper mauris semper. Nulla ullamcorper aliquet iaculis. Phasellus ut facilisis lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt, neque vel euismod auctor, tortor purus ullamcorper justo, vitae finibus leo ipsum tristique nibh. Duis faucibus vitae felis ac consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec viverra sem. Ut a magna vel elit consequat bibendum id eget magna. Aenean suscipit suscipit libero, vel dignissim neque. Ut eu purus ipsum. Cras condimentum vel risus quis tincidunt. Nulla facilisi. Nullam nec aliquet massa. Integer quis condimentum risus, sed venenatis lacus.
    </p>
    <p>
      Aliquam tristique turpis nisl, ut accumsan elit tempor at. In hac habitasse platea dictumst. Duis et ligula arcu. Praesent mattis eleifend sollicitudin. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas efficitur lectus diam. Sed arcu tellus, porta a tincidunt quis, finibus efficitur ligula. Morbi dignissim sit amet sem non dapibus. Integer ac imperdiet libero.
    </p>
  </summary>
  <educations type="academic">
    <education start="2017" end="Actualidad">
      <course>Grado en Ingeniería Informática</course>
      <institution>Universitat Oberta de Catalunya</institution>
    </education>
    <education start="2010" end="2012">
      <course>CGFS Desarrollo de aplicaciones informáticas</course>
      <institution>IES Azarquiel, Toledo</institution>
    </education>
  </educations>
  <educations type="complementary">
    <education start="2013" end="2014">
      <course>Cisco CCNA Exploration 1: Network Fundamentals</course>
      <institution>IES Azarquiel, Toledo</institution>
    </education>
    <education start="05-2013" end="06-2013">
      <course>Diseño de páginas web (Dreamweaver, Photoshop, Flash)</course>
      <institution>Forem Castilla - La Mancha, Toledo</institution>
    </education>
  </educations>
  <experiences>
    <experience>
      <company>Dematic</company>
      <projects>
	<project title="Dematic iQ" workplace="Coslada" start="06-2019" end="Actualidad">
	  <description>
	    <p>
	      Desarrollo e implantación de control de almacenes logísticos mediante Java EE utilizando diferentes especificaciones (Jersey, JMS,...).
	    </p>
	  </description>
	</project>
	<project title="Alimerka" workplace="Lugo de llanera, Asturias" start="08-2019" end="08-2019">
	  <description>
	    <p>
	      Puesta en marcha de la instalación realizando diferentes pruebas sobre el hardware real.
	    </p>
	  </description>
	</project>
      </projects>
    </experience>
    <experience>
      <company>atSistemas</company>
      <projects>
	<project title="atresmedia soluciones digitales" workplace="San Sebastián de los Reyes" start="05-2017" end="06-2019">
	  <description>
	    <p>
	      Desarrollo de aplicaciones de gestión de contenidos en código Java EE con Spring y maven utilizando BBDD oracle, MongoDB y Solr e integración con entorno Amazon AWS.
	    </p>

	    <p>
	      Diseño de frontends con GWT con utilización de clasess CSS propias y hojas de estilo externas.
	    </p>

	    <p>
	      Desarrollo de servicios REST utilizando Spring en un entorno orientado al microservicio.
	    </p>

	    <p>
	      Desarrollo de skills para Alexa utilizando el stack de AWS (Lambda, API Gateway, ElasticCache, DynamoDB, etc.).
	    </p>
	  </description>
	</project>
      </projects>
    </experience>
  </experiences>
  <languages>
    <language level="Nativo">Castellano</language>
    <language level="C1 (Cambridge First Certificate in English, FCE Grade A)">Inglés</language>
  </languages>
  <skills>
    <skill>Manejo avanzado de Office y otras herramientas ofimáticas.</skill>
    <skill>Conocimientos en diseño e instalación de redes.</skill>
    <skill>Manejo de diferentes sistemas operativos Windows</skill>
    <skill>Manejo de sistemas operativos tipo Unix en consola y X Windows</skill>
    <skill>Conocimientos de programación en lenguajes estructurados con orientación a objetos.</skill>
    <skill>Conocimiento de la sintaxis de varios lenguajes de programación (COBOL, JAVA, Visual Basic, C, C#, Ruby, HTML, CSS, JavaScript y PLSQL)</skill>
    <skill>Manejo de bases de datos (Oracle, MySQL, postgres, Access)</skill>
    <skill>Conocimientos de tecnología y estructura de computadores</skill>
    <skill>Conocimientos sobre análisis de aplicaciones</skill>
    <skill>Conocimientos de lenguajes de programación funcionales (Haskell, Lisp, Clojure).</skill>
  </skills>
</cv>
